### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
This should help you manage "metadata" in a central place for deployment to Google Play (might need the Fastlane binaries), provide them for [F-Droid](https://f-droid.org/) should you consider a listing there – and until then for [your app's listing in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.g00fy2.developerwidget). At the same time it gives an easy clue to potential contributors feeding more translations for this :wink:

You might also consider adding more details – e.g. moving screenshots inside this structure, a featureGraphic, provide per-release changelogs… [My cheat-sheet](https://gitlab.com/snippets/1895688) could provide an easy guide for that.

I hope you like the idea – and look forward to seeing this merged :smiley:

### CODE REVIEW

**Comment by G00fY2** [comment]
Hi, thanks for your input and you PR! I appreciate you added my app to your repo.

Actually I already started setting up F-Droid back then. But I really don't like the way they handle the build process. I always use the latest Gradle RC, because I use this project as a playground to test the latest versions. I find it very unhandy how the froidserver verifies Gradle versions. I had to [open a PR](https://github.com/f-droid/fdroidserver/commit/48fce5f6bea8d6903fdd25cb61a73669d2c57a3f) for each new version.

Not sure if things changed. But in the end I was to lazy to get around all of this. :sweat_smile:

I also already considered integrating fastlane. Because of my rahter low release frequnecy and the fact that I only maintain Github and PlayStore descriptions, I stepd away from it. But it's still on my list! So thanks again for you first step!

**Comment by IzzySoft** [comment]
Afraid concerning the build processes handling of gradle not much has changed. The "always latest" always is a version not yet open-sourced, so it cannot be used by F-Droid.

If Fastlane is still on your list, this PR will be a good starting point for 2 languages even :smiley: So will you merge it?

**Comment by IzzySoft** [comment]
@G00fY2 Was it lost somehow? Do you need something more to merge this PR?

**Comment by IzzySoft** [comment]
@G00fY2 A little heads-up: My repo uses Fastlane, too, so I'd appreciate this being merged :smiley:

> Because of my rahter low release frequnecy

Well, then you don't have to fear you'd have to frequently update Fastlane descriptions either, right? :laughing:

> and the fact that I only maintain Github and PlayStore descriptions

Well… Fastlane was written with PlayStore in mind. So if you'd maintain descriptions (and screenshots) for Play via Fastlane, you'd catch another bird with the same stone: my repo. [Your app is here](https://apt.izzysoft.de/fdroid/index/apk/com.g00fy2.developerwidget).

> But it's still on my list!

Glad to read! :green_heart: Then merging this would be a good first step :wink: Apologies for nagging, but once this is merged I could cleanup on my end, adjust your app's metadata, and have one item off my list…

**Comment by G00fY2** [comment]
Hi @IzzySoft, sorry for replying so late.

I didn't knew that you rely on my fastlane setup for having my app in your F-Droid repo (that is how it is, right?).

Ofc I will merge your PR, but I am still not sure when I will acutally make use of the features like automating my releases/deployments. 😃

Thanks again for your contribution!

Btw: Do you need this on the master branch right now aswell?

**Comment by IzzySoft** [comment]
> I didn't knew that you rely on my fastlane setup for having my app in your F-Droid repo

Not that strong. Actually, in the past I often noticed I missed updating app descriptions, screenshots and the like because I didn't notice there *were* updates. Using Fastlane gives a defined (and standardized) way to avoid that: those who develop/maintain the app usually know when things changed. So if you update your app's description/screenshots you know that you're doing so. Doing that in Fastlane stuctures means that when my updater pulls the next release, those changes get pulled along.

The basics (short/fulldesc) are most important, so the actual status is reflected. Screenshots would be nice – but if they're not contained, users will better recognize that than a missed description item :wink:

> I am still not sure when I will acutally make use of the features like automating my releases/deployments

That won't at least be worse than before, right? And the `fastlane` directory being present at top-level of your repo might be a good reminder :laughing:

> Do you need this on the master branch right now aswell?

Nope. Other than F-Droid, I pull Fastlane from a "fixed URL" – and I've now copied the one present. As long as Github's API can handle that (which remains to be seen: for several things, they don't handle branches well), all should be fine. We'll see on the next update, whether fastlane was changed or not: if my updater fails to check, it will yell. If it doesn't yell, all should be well. If it does yell, I will do tell!

Thanks for merging! I've anchored the Fastlane location now in your app's metadata, so it should be in effect already. And I now can clean up some more temp folders on my end :wink:

**Comment by IzzySoft** [comment]
PS: should you add screenshots to the new fastlane structures, please let me know so I can reflect that here, too.

**Pull request merged**
